# Generated by Django 5.0.2 on 2024-03-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=10)),
            ],
        ),
    ]
